
ropa = {'camiseta': 0,
 'sombrero': 1,
 'reloj masculino': 2,
 'Anillo': 3,
 'manga_larga': 4,
 'chaquetas': 5,
 'pulsera masculina': 6,
 'camisa': 7,
 'pantalon': 8,
 'anillo de boda': 9,
 'bermuda': 10,
 'zapato': 11,
 'Collar con colgante': 12,
 'vestido': 13,
 'falda': 14}

clothing = {'t-shirt': 0,
 'hat': 1,
 'men watch': 2,
 'ring': 3,
 'long sleeve': 4,
 'jackets': 5,
 'men bracelet': 6,
 'shirt': 7,
 'pants': 8,
 'wedding ring': 9,
 'bermuda shorts': 10,
 'shoe': 11,
 'pendant necklace': 12,
 'dress': 13,
 'skirt': 14}
